name: rutina_diaria
description: "Daylyo - Construye hábitos, día a día"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  google_fonts: ^6.1.0
  flutter_local_notifications: ^17.1.2
  google_mobile_ads: ^3.1.0
  confetti: ^0.7.0
  intl: ^0.20.2
  timezone: ^0.9.2
  uuid: ^4.4.0
  collection: ^1.18.0
  home_widget: ^0.8.1
  file_picker: ^8.1.4
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/app/

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/app/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
